### ISSUE TITLE
Username or Password is incorrect

### ISSUE THREAD

**Issue by AbirHasanSamir** [NawabHost/bkash-merchant-for-whmcs#1]
All the credentials are perfect. But showing Username or Password is incorrect. Checkout option working perfectly. But legacy not working https://prnt.sc/EPuKsBwusR3s
@AminulBD

**Comment by AminulBD** [comment]
You can't use the legacy username on the checkout method or you can't use checkout access to the legacy method. You must have to contact bKash first.
